---
version: '3.8'
services:
  building:
    build: .
    volumes:
      - type: volume
        source: warnik
        target: /warnik
      
  prod:
    image: tomcat:9.0.67-jre11
    volumes:
      - type: volume
        source: warnik
        target: /usr/local/tomcat/webapps/
    ports:
      - "8081:8080"

volumes:
  warnik:
    
